In [5]:
##Tokenization
import nltk
nltk.download('punkt')
text = "You will improve your reading comprehension and develop your vocabulary on a diverse range of international events, celebrations and topics."

words = nltk.word_tokenize(text)
words

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['You',
 'will',
 'improve',
 'your',
 'reading',
 'comprehension',
 'and',
 'develop',
 'your',
 'vocabulary',
 'on',
 'a',
 'diverse',
 'range',
 'of',
 'international',
 'events',
 ',',
 'celebrations',
 'and',
 'topics',
 '.']

In [17]:
## Stemming
ps = nltk.porter.PorterStemmer()
ps_text = [ps.stem(word) for word in words
' '.join(ps_text)

'you will improv your read comprehens and develop your vocabulari on a divers rang of intern event , celebr and topic .'

In [23]:
#Lemmatization
lem = nltk.WordNetLemmatizer()
lem_text = [lem.lemmatize(word) for word in words]
' '.join(lem_text)

'You will improve your reading comprehension and develop your vocabulary on a diverse range of international event , celebration and topic .'

In [25]:
## remove stopwords 
import string 
nltk.download('stopwords')
stopword_list = set(nltk.corpus.stopwords.words('english')+ list(string.punctuation))
filter_tokens = [token for token in lem_text if token not in stopword_list]
filter_text = ' '.join(filter_tokens)
filter_tokens


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['You',
 'improve',
 'reading',
 'comprehension',
 'develop',
 'vocabulary',
 'diverse',
 'range',
 'international',
 'event',
 'celebration',
 'topic']

In [32]:
## BOW
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

corpus = ["Today is a good day.",
         "Yesterday was a cloudy day.",
         "Hope tommrow will be a good day."]

vectorizer = CountVectorizer()
x = vectorizer.fit_transform(corpus)

word = vectorizer.get_feature_names()
print("Vocabulary: \n", word)
print("BOW: \n", x.toarray())

Vocabulary: 
 ['be', 'cloudy', 'day', 'good', 'hope', 'is', 'today', 'tommrow', 'was', 'will', 'yesterday']
BOW: 
 [[0 0 1 1 0 1 1 0 0 0 0]
 [0 1 1 0 0 0 0 0 1 0 1]
 [1 0 1 1 1 0 0 1 0 1 0]]


In [36]:
## TF-IDF
import numpy as np
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(x)
print("TF-IDF: \n", np.around(tfidf.toarray(),2))

TF-IDF: 
 [[0.   0.   0.35 0.44 0.   0.58 0.58 0.   0.   0.   0.  ]
 [0.   0.55 0.32 0.   0.   0.   0.   0.   0.55 0.   0.55]
 [0.45 0.   0.27 0.34 0.45 0.   0.   0.45 0.   0.45 0.  ]]
